# Generated by Django 5.1.3 on 2025-03-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='algoritmos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='estruturaDeDados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='matematica',
            field=models.IntegerField(default=0),
        ),
    ]
